### ISSUE TITLE
Python Run Issue

### ISSUE THREAD

**Issue by RanitPradhan** [RanitPradhan/Academics#9]
![git-issue](https://user-images.githubusercontent.com/56351938/183895275-0f5ae532-20dc-4769-9add-f555a101a29f.png)

Worked with C++ but showed this problem with python 3.

Python code:
```python
def findZigZagSequence(a, n):
    a.sort()
    mid = int(n/2) #changed
    a[mid], a[n-1] = a[n-1], a[mid]
    st = mid + 1
    ed = n - 2 #changed
    while(st <= ed):
        a[st], a[ed] = a[ed], a[st]
        st = st + 1
        ed = ed - 1 #changed

    for i in range (n):
        if i == n-1:
            print(a[i])
        else:
            print(a[i], end = ' ')
    return

test_cases = int(input())
for cs in range (test_cases):
    n = int(input())
    a = list(map(int, input().split()))
    findZigZagSequence(a, n)
```

**Comment by VenkateshSoni** [comment]
Can you share the problem statement or the link to problem?

**Comment by RanitPradhan** [comment]
Yes, sure.
[Link](https://www.hackerrank.com/challenges/one-week-preparation-kit-zig-zag-sequence/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=one-week-preparation-kit&playlist_slugs%5B%5D=one-week-day-three)

**Comment by VenkateshSoni** [comment]
Is the issue solved? As I can see the debugged code by you here works perfectly.

**Comment by RanitPradhan** [comment]
No, it's not solved actually. I can't get what's the issue. The same calculations worked properly in C++ but no idea what's wrong with Python3 here.

**Comment by VenkateshSoni** [comment]
You have made a simple error; the problem statement says that you cannot add or delete any lines of code. But you have **removed a blank line number 5**, if you look closely the original given code.

```
def findZigZagSequence(a, n):
    a.sort()
    mid = int(n/2) #changed
    a[mid], a[n-1] = a[n-1], a[mid]
#-------------------------------------you dont have this line in your code ---------------------------------
    st = mid + 1
    ed = n - 2 #changed
    while(st <= ed):
        a[st], a[ed] = a[ed], a[st]
        st = st + 1
        ed = ed - 1 #changed

    for i in range (n):
        if i == n-1:
            print(a[i])
        else:
            print(a[i], end = ' ')
    return

test_cases = int(input())
for cs in range (test_cases):
    n = int(input())
    a = list(map(int, input().split()))
    findZigZagSequence(a, n)
```
I hope this answer is sufficient to solve your issue.

**Comment by RanitPradhan** [comment]
OMG ! That was really crazy xD
Thanks mate 🤝

**Comment by VenkateshSoni** [comment]
You're welcome :)
